name: 'Publish to PowerShell Gallery'
description: 'Publishing your module to the PowerShell Gallery'
author: 'Einar Stenberg based on the work by Shawn Melton'
inputs:
  apiKey:
    description: 'PowerShell Gallery API Key for publishing to your account'
    required: true
runs:
  using: 'docker'
  image: 'dockerfile'
  args:
    - ${{ inputs.tags }}
    - ${{ inputs.apiKey }}
branding:
  icon: 'upload'
  color: 'blue'
