name: Deploy to Psgallery
on: [push]
jobs:
  deploy:
    name: deploying
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v1
      - name: deploy
        uses: ovrap3x/psgallerypublish-docker@master
        with:
          #tags: test1
          apiKey: ${{secrets.APIKEY}}
        
