name: Deploy to Psgallery
on: [push]
jobs:
  deploy:
    name: deploying
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v1
      - name: deploy
        uses: docker.pkg.github.com/ovrap3x/psgallerypublish-docker@latest
        with:
          tags: powershell
          apiKey: ${{secrets.APIKEY}}
        
